export const reportSummaryData = {
  cibil: {
    currentScore: {
      score: 820,
      status: "Excellent",
      color: "#4AD170",
    },
    monthylScores: [
      { month: "Aug", score: 710 },
      { month: "Sep", score: 720 },
      { month: "Oct", score: 680 },
      { month: "Nov", score: 773 },
      { month: "Dec", score: 820 },
    ],
    whatChanged: [
      {
        id: "1",
        icon: "P",
        name: "Payment",
        impact: "High Impact",
        value: "100%",
        remark: "Timely Payment",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "2",
        icon: "L",
        name: "Limit",
        impact: "High Impact",
        value: "8%",
        remark: "credit limit used",
        ontime: false,
        message: "All payments are not on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "3",
        icon: "A",
        name: "Age",
        impact: "Medium Impact",
        value: "100%",
        remark: "Timely Payment",
        ontime: false,
        message: "All payments are not on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "4",
        icon: "A",
        name: "Accounts",
        impact: "Low Impact",
        value: "5 Active",
        remark: "Active Accounts",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "5",
        icon: "E",
        name: "Enquiries",
        impact: "Low Impact",
        value: "2",
        remark: "Total Enquiries",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "6",
        icon: "P",
        name: "Profile",
        impact: "Low Impact",
        value: "1",
        remark: "Derogatory Marks",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
    ],
  },
  experian: {
    currentScore: {
      score: 820,
      status: "Excellent",
      color: "#4AD170",
    },
    monthylScores: [
      { month: "Aug", score: 710 },
      { month: "Sep", score: 720 },
      { month: "Oct", score: 680 },
      { month: "Nov", score: 773 },
      { month: "Dec", score: 820 },
    ],
    whatChanged: [
      {
        id: "1",
        icon: "P",
        name: "Payment",
        impact: "High Impact",
        value: "100%",
        remark: "Timely Payment",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "2",
        icon: "L",
        name: "Limit",
        impact: "High Impact",
        value: "8%",
        remark: "credit limit used",
        ontime: false,
        message: "All payments are not on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "3",
        icon: "A",
        name: "Age",
        impact: "Medium Impact",
        value: "100%",
        remark: "Timely Payment",
        ontime: false,
        message: "All payments are not on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "4",
        icon: "A",
        name: "Accounts",
        impact: "Low Impact",
        value: "5 Active",
        remark: "Active Accounts",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "5",
        icon: "E",
        name: "Enquiries",
        impact: "Low Impact",
        value: "2",
        remark: "Total Enquiries",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
      {
        id: "6",
        icon: "P",
        name: "Profile",
        impact: "Low Impact",
        value: "1",
        remark: "Derogatory Marks",
        ontime: true,
        message: "All payments are on time",
        impacts: {
          latePaymentsCount: 5,
          percentOnTime: 80,
          status: "Excellent",
        },
      },
    ],
  },
};
