export const viewImapact = {
  1: {
    headText: "Your Accounts",
    accounts: [
      {
        id: "1",
        icon: "P",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: false,
        statusText: "Status",
        statusValue: "In-Active",
        isActive: false,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "1",
        icon: "P",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: false,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "2",
        icon: "L",
        name: "Axis Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "3",
        icon: "A",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Personal Loan",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "In-Active",
        isActive: false,
        payment: "5/5",
        remark: "Timely Payment",
      },
    ],
  },
  2: {
    headText: "Your Accounts",
    accounts: [
      {
        id: "1",
        icon: "P",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: false,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "2",
        icon: "L",
        name: "Axis Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "3",
        icon: "A",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Personal Loan",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "In-Active",
        isActive: false,
        payment: "5/5",
        remark: "Timely Payment",
      },
    ],
  },
  3: {
    headText: "Your Accounts",
    accounts: [
      {
        id: "1",
        icon: "P",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: false,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "3",
        icon: "A",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Personal Loan",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "In-Active",
        isActive: false,
        payment: "5/5",
        remark: "Timely Payment",
      },
    ],
  },
  4: {
    headText: "Your Accounts",
    accounts: [
      {
        id: "1",
        icon: "P",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: false,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "2",
        icon: "L",
        name: "Axis Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "3",
        icon: "A",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Personal Loan",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "In-Active",
        isActive: false,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "2",
        icon: "L",
        name: "Axis Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
    ],
  },
  5: {
    headText: "Your Accounts",
    accounts: [
      {
        id: "1",
        icon: "P",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: false,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "2",
        icon: "L",
        name: "Axis Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
    ],
  },
  6: {
    headText: "Your Accounts",
    accounts: [
      {
        id: "2",
        icon: "L",
        name: "Axis Bank",
        issueOn: "23-01-1998",
        bankUtil: "Credit Card",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "Active",
        isActive: true,
        payment: "5/5",
        remark: "Timely Payment",
      },
      {
        id: "3",
        icon: "A",
        name: "ICICI Bank",
        issueOn: "23-01-1998",
        bankUtil: "Personal Loan",
        bankUtilValue: "**** 2222",
        isExpandable: true,
        statusText: "Status",
        statusValue: "In-Active",
        isActive: false,
        payment: "5/5",
        remark: "Timely Payment",
      },
    ],
  },
};
